/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWeldsRouteImport } from './routes/app.welds'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQualificationsRouteImport } from './routes/app.qualifications'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppProceduresRouteImport } from './routes/app.procedures'
import { Route as AppInstrumentsRouteImport } from './routes/app.instruments'
import { Route as AppInspectionsRouteImport } from './routes/app.inspections'
import { Route as AppEquipmentRouteImport } from './routes/app.equipment'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as VerifyInstrumentTokenRouteImport } from './routes/verify.instrument.$token'
import { Route as AppReportsSlugRouteImport } from './routes/app.reports.$slug'
import { Route as AppProceduresProcedureIdRouteImport } from './routes/app.procedures.$procedureId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeldsRoute = AppWeldsRouteImport.update({
  id: '/welds',
  path: '/welds',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQualificationsRoute = AppQualificationsRouteImport.update({
  id: '/qualifications',
  path: '/qualifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProceduresRoute = AppProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => AppRoute,
} as any)
const AppInstrumentsRoute = AppInstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const VerifyInstrumentTokenRoute = VerifyInstrumentTokenRouteImport.update({
  id: '/verify/instrument/$token',
  path: '/verify/instrument/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsSlugRoute = AppReportsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppProceduresProcedureIdRoute =
  AppProceduresProcedureIdRouteImport.update({
    id: '/$procedureId',
    path: '/$procedureId',
    getParentRoute: () => AppProceduresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/audit': typeof AppAuditRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/instruments': typeof AppInstrumentsRoute
  '/app/procedures': typeof AppProceduresRouteWithChildren
  '/app/projects': typeof AppProjectsRoute
  '/app/qualifications': typeof AppQualificationsRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/welds': typeof AppWeldsRoute
  '/app/': typeof AppIndexRoute
  '/app/procedures/$procedureId': typeof AppProceduresProcedureIdRoute
  '/app/reports/$slug': typeof AppReportsSlugRoute
  '/verify/instrument/$token': typeof VerifyInstrumentTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/audit': typeof AppAuditRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/instruments': typeof AppInstrumentsRoute
  '/app/procedures': typeof AppProceduresRouteWithChildren
  '/app/projects': typeof AppProjectsRoute
  '/app/qualifications': typeof AppQualificationsRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/welds': typeof AppWeldsRoute
  '/app': typeof AppIndexRoute
  '/app/procedures/$procedureId': typeof AppProceduresProcedureIdRoute
  '/app/reports/$slug': typeof AppReportsSlugRoute
  '/verify/instrument/$token': typeof VerifyInstrumentTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/audit': typeof AppAuditRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/instruments': typeof AppInstrumentsRoute
  '/app/procedures': typeof AppProceduresRouteWithChildren
  '/app/projects': typeof AppProjectsRoute
  '/app/qualifications': typeof AppQualificationsRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/welds': typeof AppWeldsRoute
  '/app/': typeof AppIndexRoute
  '/app/procedures/$procedureId': typeof AppProceduresProcedureIdRoute
  '/app/reports/$slug': typeof AppReportsSlugRoute
  '/verify/instrument/$token': typeof VerifyInstrumentTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/audit'
    | '/app/equipment'
    | '/app/inspections'
    | '/app/instruments'
    | '/app/procedures'
    | '/app/projects'
    | '/app/qualifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/welds'
    | '/app/'
    | '/app/procedures/$procedureId'
    | '/app/reports/$slug'
    | '/verify/instrument/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/audit'
    | '/app/equipment'
    | '/app/inspections'
    | '/app/instruments'
    | '/app/procedures'
    | '/app/projects'
    | '/app/qualifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/welds'
    | '/app'
    | '/app/procedures/$procedureId'
    | '/app/reports/$slug'
    | '/verify/instrument/$token'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/audit'
    | '/app/equipment'
    | '/app/inspections'
    | '/app/instruments'
    | '/app/procedures'
    | '/app/projects'
    | '/app/qualifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/welds'
    | '/app/'
    | '/app/procedures/$procedureId'
    | '/app/reports/$slug'
    | '/verify/instrument/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyInstrumentTokenRoute: typeof VerifyInstrumentTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/welds': {
      id: '/app/welds'
      path: '/welds'
      fullPath: '/app/welds'
      preLoaderRoute: typeof AppWeldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qualifications': {
      id: '/app/qualifications'
      path: '/qualifications'
      fullPath: '/app/qualifications'
      preLoaderRoute: typeof AppQualificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procedures': {
      id: '/app/procedures'
      path: '/procedures'
      fullPath: '/app/procedures'
      preLoaderRoute: typeof AppProceduresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instruments': {
      id: '/app/instruments'
      path: '/instruments'
      fullPath: '/app/instruments'
      preLoaderRoute: typeof AppInstrumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspections': {
      id: '/app/inspections'
      path: '/inspections'
      fullPath: '/app/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipment': {
      id: '/app/equipment'
      path: '/equipment'
      fullPath: '/app/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/verify/instrument/$token': {
      id: '/verify/instrument/$token'
      path: '/verify/instrument/$token'
      fullPath: '/verify/instrument/$token'
      preLoaderRoute: typeof VerifyInstrumentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports/$slug': {
      id: '/app/reports/$slug'
      path: '/$slug'
      fullPath: '/app/reports/$slug'
      preLoaderRoute: typeof AppReportsSlugRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/procedures/$procedureId': {
      id: '/app/procedures/$procedureId'
      path: '/$procedureId'
      fullPath: '/app/procedures/$procedureId'
      preLoaderRoute: typeof AppProceduresProcedureIdRouteImport
      parentRoute: typeof AppProceduresRoute
    }
  }
}

interface AppProceduresRouteChildren {
  AppProceduresProcedureIdRoute: typeof AppProceduresProcedureIdRoute
}

const AppProceduresRouteChildren: AppProceduresRouteChildren = {
  AppProceduresProcedureIdRoute: AppProceduresProcedureIdRoute,
}

const AppProceduresRouteWithChildren = AppProceduresRoute._addFileChildren(
  AppProceduresRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsSlugRoute: typeof AppReportsSlugRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsSlugRoute: AppReportsSlugRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppInstrumentsRoute: typeof AppInstrumentsRoute
  AppProceduresRoute: typeof AppProceduresRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRoute
  AppQualificationsRoute: typeof AppQualificationsRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWeldsRoute: typeof AppWeldsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppInstrumentsRoute: AppInstrumentsRoute,
  AppProceduresRoute: AppProceduresRouteWithChildren,
  AppProjectsRoute: AppProjectsRoute,
  AppQualificationsRoute: AppQualificationsRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppWeldsRoute: AppWeldsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyInstrumentTokenRoute: VerifyInstrumentTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
