/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWeldsRouteImport } from './routes/app.welds'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQualificationsRouteImport } from './routes/app.qualifications'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppProceduresRouteImport } from './routes/app.procedures'
import { Route as AppNcrsRouteImport } from './routes/app.ncrs'
import { Route as AppInstrumentsRouteImport } from './routes/app.instruments'
import { Route as AppInspectionsRouteImport } from './routes/app.inspections'
import { Route as AppEquipmentRouteImport } from './routes/app.equipment'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as VerifyWeldTokenRouteImport } from './routes/verify.weld.$token'
import { Route as VerifyInstrumentTokenRouteImport } from './routes/verify.instrument.$token'
import { Route as AppWeldsWeldIdRouteImport } from './routes/app.welds.$weldId'
import { Route as AppReportsSlugRouteImport } from './routes/app.reports.$slug'
import { Route as AppProceduresProcedureIdRouteImport } from './routes/app.procedures.$procedureId'
import { Route as AppNcrsNcrIdRouteImport } from './routes/app.ncrs.$ncrId'
import { Route as AppInstrumentsInstrumentIdRouteImport } from './routes/app.instruments.$instrumentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeldsRoute = AppWeldsRouteImport.update({
  id: '/welds',
  path: '/welds',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQualificationsRoute = AppQualificationsRouteImport.update({
  id: '/qualifications',
  path: '/qualifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProceduresRoute = AppProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => AppRoute,
} as any)
const AppNcrsRoute = AppNcrsRouteImport.update({
  id: '/ncrs',
  path: '/ncrs',
  getParentRoute: () => AppRoute,
} as any)
const AppInstrumentsRoute = AppInstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const VerifyWeldTokenRoute = VerifyWeldTokenRouteImport.update({
  id: '/verify/weld/$token',
  path: '/verify/weld/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyInstrumentTokenRoute = VerifyInstrumentTokenRouteImport.update({
  id: '/verify/instrument/$token',
  path: '/verify/instrument/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeldsWeldIdRoute = AppWeldsWeldIdRouteImport.update({
  id: '/$weldId',
  path: '/$weldId',
  getParentRoute: () => AppWeldsRoute,
} as any)
const AppReportsSlugRoute = AppReportsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppProceduresProcedureIdRoute =
  AppProceduresProcedureIdRouteImport.update({
    id: '/$procedureId',
    path: '/$procedureId',
    getParentRoute: () => AppProceduresRoute,
  } as any)
const AppNcrsNcrIdRoute = AppNcrsNcrIdRouteImport.update({
  id: '/$ncrId',
  path: '/$ncrId',
  getParentRoute: () => AppNcrsRoute,
} as any)
const AppInstrumentsInstrumentIdRoute =
  AppInstrumentsInstrumentIdRouteImport.update({
    id: '/$instrumentId',
    path: '/$instrumentId',
    getParentRoute: () => AppInstrumentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/instruments': typeof AppInstrumentsRouteWithChildren
  '/app/ncrs': typeof AppNcrsRouteWithChildren
  '/app/procedures': typeof AppProceduresRouteWithChildren
  '/app/projects': typeof AppProjectsRoute
  '/app/qualifications': typeof AppQualificationsRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/welds': typeof AppWeldsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/instruments/$instrumentId': typeof AppInstrumentsInstrumentIdRoute
  '/app/ncrs/$ncrId': typeof AppNcrsNcrIdRoute
  '/app/procedures/$procedureId': typeof AppProceduresProcedureIdRoute
  '/app/reports/$slug': typeof AppReportsSlugRoute
  '/app/welds/$weldId': typeof AppWeldsWeldIdRoute
  '/verify/instrument/$token': typeof VerifyInstrumentTokenRoute
  '/verify/weld/$token': typeof VerifyWeldTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/instruments': typeof AppInstrumentsRouteWithChildren
  '/app/ncrs': typeof AppNcrsRouteWithChildren
  '/app/procedures': typeof AppProceduresRouteWithChildren
  '/app/projects': typeof AppProjectsRoute
  '/app/qualifications': typeof AppQualificationsRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/welds': typeof AppWeldsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/instruments/$instrumentId': typeof AppInstrumentsInstrumentIdRoute
  '/app/ncrs/$ncrId': typeof AppNcrsNcrIdRoute
  '/app/procedures/$procedureId': typeof AppProceduresProcedureIdRoute
  '/app/reports/$slug': typeof AppReportsSlugRoute
  '/app/welds/$weldId': typeof AppWeldsWeldIdRoute
  '/verify/instrument/$token': typeof VerifyInstrumentTokenRoute
  '/verify/weld/$token': typeof VerifyWeldTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/instruments': typeof AppInstrumentsRouteWithChildren
  '/app/ncrs': typeof AppNcrsRouteWithChildren
  '/app/procedures': typeof AppProceduresRouteWithChildren
  '/app/projects': typeof AppProjectsRoute
  '/app/qualifications': typeof AppQualificationsRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/welds': typeof AppWeldsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/instruments/$instrumentId': typeof AppInstrumentsInstrumentIdRoute
  '/app/ncrs/$ncrId': typeof AppNcrsNcrIdRoute
  '/app/procedures/$procedureId': typeof AppProceduresProcedureIdRoute
  '/app/reports/$slug': typeof AppReportsSlugRoute
  '/app/welds/$weldId': typeof AppWeldsWeldIdRoute
  '/verify/instrument/$token': typeof VerifyInstrumentTokenRoute
  '/verify/weld/$token': typeof VerifyWeldTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/app'
    | '/contact'
    | '/demo'
    | '/features'
    | '/industries'
    | '/login'
    | '/modules'
    | '/pricing'
    | '/signup'
    | '/app/admin'
    | '/app/audit'
    | '/app/billing'
    | '/app/equipment'
    | '/app/inspections'
    | '/app/instruments'
    | '/app/ncrs'
    | '/app/procedures'
    | '/app/projects'
    | '/app/qualifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/welds'
    | '/app/'
    | '/app/instruments/$instrumentId'
    | '/app/ncrs/$ncrId'
    | '/app/procedures/$procedureId'
    | '/app/reports/$slug'
    | '/app/welds/$weldId'
    | '/verify/instrument/$token'
    | '/verify/weld/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-invite'
    | '/contact'
    | '/demo'
    | '/features'
    | '/industries'
    | '/login'
    | '/modules'
    | '/pricing'
    | '/signup'
    | '/app/admin'
    | '/app/audit'
    | '/app/billing'
    | '/app/equipment'
    | '/app/inspections'
    | '/app/instruments'
    | '/app/ncrs'
    | '/app/procedures'
    | '/app/projects'
    | '/app/qualifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/welds'
    | '/app'
    | '/app/instruments/$instrumentId'
    | '/app/ncrs/$ncrId'
    | '/app/procedures/$procedureId'
    | '/app/reports/$slug'
    | '/app/welds/$weldId'
    | '/verify/instrument/$token'
    | '/verify/weld/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accept-invite'
    | '/app'
    | '/contact'
    | '/demo'
    | '/features'
    | '/industries'
    | '/login'
    | '/modules'
    | '/pricing'
    | '/signup'
    | '/app/admin'
    | '/app/audit'
    | '/app/billing'
    | '/app/equipment'
    | '/app/inspections'
    | '/app/instruments'
    | '/app/ncrs'
    | '/app/procedures'
    | '/app/projects'
    | '/app/qualifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/team'
    | '/app/welds'
    | '/app/'
    | '/app/instruments/$instrumentId'
    | '/app/ncrs/$ncrId'
    | '/app/procedures/$procedureId'
    | '/app/reports/$slug'
    | '/app/welds/$weldId'
    | '/verify/instrument/$token'
    | '/verify/weld/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  ModulesRoute: typeof ModulesRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  VerifyInstrumentTokenRoute: typeof VerifyInstrumentTokenRoute
  VerifyWeldTokenRoute: typeof VerifyWeldTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/welds': {
      id: '/app/welds'
      path: '/welds'
      fullPath: '/app/welds'
      preLoaderRoute: typeof AppWeldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qualifications': {
      id: '/app/qualifications'
      path: '/qualifications'
      fullPath: '/app/qualifications'
      preLoaderRoute: typeof AppQualificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procedures': {
      id: '/app/procedures'
      path: '/procedures'
      fullPath: '/app/procedures'
      preLoaderRoute: typeof AppProceduresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ncrs': {
      id: '/app/ncrs'
      path: '/ncrs'
      fullPath: '/app/ncrs'
      preLoaderRoute: typeof AppNcrsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/instruments': {
      id: '/app/instruments'
      path: '/instruments'
      fullPath: '/app/instruments'
      preLoaderRoute: typeof AppInstrumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspections': {
      id: '/app/inspections'
      path: '/inspections'
      fullPath: '/app/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipment': {
      id: '/app/equipment'
      path: '/equipment'
      fullPath: '/app/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/verify/weld/$token': {
      id: '/verify/weld/$token'
      path: '/verify/weld/$token'
      fullPath: '/verify/weld/$token'
      preLoaderRoute: typeof VerifyWeldTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/instrument/$token': {
      id: '/verify/instrument/$token'
      path: '/verify/instrument/$token'
      fullPath: '/verify/instrument/$token'
      preLoaderRoute: typeof VerifyInstrumentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/welds/$weldId': {
      id: '/app/welds/$weldId'
      path: '/$weldId'
      fullPath: '/app/welds/$weldId'
      preLoaderRoute: typeof AppWeldsWeldIdRouteImport
      parentRoute: typeof AppWeldsRoute
    }
    '/app/reports/$slug': {
      id: '/app/reports/$slug'
      path: '/$slug'
      fullPath: '/app/reports/$slug'
      preLoaderRoute: typeof AppReportsSlugRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/procedures/$procedureId': {
      id: '/app/procedures/$procedureId'
      path: '/$procedureId'
      fullPath: '/app/procedures/$procedureId'
      preLoaderRoute: typeof AppProceduresProcedureIdRouteImport
      parentRoute: typeof AppProceduresRoute
    }
    '/app/ncrs/$ncrId': {
      id: '/app/ncrs/$ncrId'
      path: '/$ncrId'
      fullPath: '/app/ncrs/$ncrId'
      preLoaderRoute: typeof AppNcrsNcrIdRouteImport
      parentRoute: typeof AppNcrsRoute
    }
    '/app/instruments/$instrumentId': {
      id: '/app/instruments/$instrumentId'
      path: '/$instrumentId'
      fullPath: '/app/instruments/$instrumentId'
      preLoaderRoute: typeof AppInstrumentsInstrumentIdRouteImport
      parentRoute: typeof AppInstrumentsRoute
    }
  }
}

interface AppInstrumentsRouteChildren {
  AppInstrumentsInstrumentIdRoute: typeof AppInstrumentsInstrumentIdRoute
}

const AppInstrumentsRouteChildren: AppInstrumentsRouteChildren = {
  AppInstrumentsInstrumentIdRoute: AppInstrumentsInstrumentIdRoute,
}

const AppInstrumentsRouteWithChildren = AppInstrumentsRoute._addFileChildren(
  AppInstrumentsRouteChildren,
)

interface AppNcrsRouteChildren {
  AppNcrsNcrIdRoute: typeof AppNcrsNcrIdRoute
}

const AppNcrsRouteChildren: AppNcrsRouteChildren = {
  AppNcrsNcrIdRoute: AppNcrsNcrIdRoute,
}

const AppNcrsRouteWithChildren =
  AppNcrsRoute._addFileChildren(AppNcrsRouteChildren)

interface AppProceduresRouteChildren {
  AppProceduresProcedureIdRoute: typeof AppProceduresProcedureIdRoute
}

const AppProceduresRouteChildren: AppProceduresRouteChildren = {
  AppProceduresProcedureIdRoute: AppProceduresProcedureIdRoute,
}

const AppProceduresRouteWithChildren = AppProceduresRoute._addFileChildren(
  AppProceduresRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsSlugRoute: typeof AppReportsSlugRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsSlugRoute: AppReportsSlugRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppWeldsRouteChildren {
  AppWeldsWeldIdRoute: typeof AppWeldsWeldIdRoute
}

const AppWeldsRouteChildren: AppWeldsRouteChildren = {
  AppWeldsWeldIdRoute: AppWeldsWeldIdRoute,
}

const AppWeldsRouteWithChildren = AppWeldsRoute._addFileChildren(
  AppWeldsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppInstrumentsRoute: typeof AppInstrumentsRouteWithChildren
  AppNcrsRoute: typeof AppNcrsRouteWithChildren
  AppProceduresRoute: typeof AppProceduresRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRoute
  AppQualificationsRoute: typeof AppQualificationsRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWeldsRoute: typeof AppWeldsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppInstrumentsRoute: AppInstrumentsRouteWithChildren,
  AppNcrsRoute: AppNcrsRouteWithChildren,
  AppProceduresRoute: AppProceduresRouteWithChildren,
  AppProjectsRoute: AppProjectsRoute,
  AppQualificationsRoute: AppQualificationsRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppWeldsRoute: AppWeldsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  ModulesRoute: ModulesRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  VerifyInstrumentTokenRoute: VerifyInstrumentTokenRoute,
  VerifyWeldTokenRoute: VerifyWeldTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
