// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

export type BootstrapError = { message: string; missing: string[] };

let _supabase: SupabaseClient<Database> | undefined;
let _bootstrapError: BootstrapError | undefined;

function tryCreate(): SupabaseClient<Database> | undefined {
  try {
    const env = (import.meta as any).env ?? {};
    const SUPABASE_URL: string | undefined =
      env.VITE_SUPABASE_URL ||
      (typeof process !== 'undefined' ? (process as any).env?.SUPABASE_URL : undefined);
    const SUPABASE_PUBLISHABLE_KEY: string | undefined =
      env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      (typeof process !== 'undefined' ? (process as any).env?.SUPABASE_PUBLISHABLE_KEY : undefined);

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      _bootstrapError = {
        message: `Missing backend environment variable(s): ${missing.join(', ')}.`,
        missing,
      };
      console.error('[Supabase bootstrap]', _bootstrapError.message);
      return undefined;
    }

    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  } catch (err: any) {
    _bootstrapError = {
      message: `Backend client failed to initialize: ${err?.message ?? String(err)}`,
      missing: [],
    };
    console.error('[Supabase bootstrap]', err);
    return undefined;
  }
}

function getOrInit(): SupabaseClient<Database> | undefined {
  if (!_supabase && !_bootstrapError) _supabase = tryCreate();
  return _supabase;
}

export function getSupabaseBootstrapError(): BootstrapError | undefined {
  // Trigger lazy init so consumers can check status at startup.
  getOrInit();
  return _bootstrapError;
}

// A safe no-op chain returned when the client is unavailable. This prevents
// any consumer from throwing synchronously during preview boot.
function unavailable(): never {
  throw new Error(
    _bootstrapError?.message ??
      'Backend client is unavailable. Check Lovable Cloud configuration.',
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    const client = getOrInit();
    if (!client) {
      // Provide a friendly thenable so accidental awaits don't crash the app.
      if (prop === 'then') return undefined;
      return unavailable;
    }
    return Reflect.get(client, prop, receiver);
  },
});
